# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-31 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer_app', '0002_author_book_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='book',
            name='uploader',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='book_uploads', to='belt_reviewer_app.User'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to='belt_reviewer_app.User'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='belt_reviewer_app.Book'),
        ),
    ]
