# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-22 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_poke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='poked_by',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='poker',
        ),
        migrations.DeleteModel(
            name='Poke',
        ),
    ]
