# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0004_poke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='counter',
        ),
    ]
