# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_author',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
