# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_auto_20171221_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
