# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0004_auto_20171221_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='belt_app.User')),
                ('users', models.ManyToManyField(to='belt_app.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='from_friend',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='to_friend',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
