# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registered_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_confirmation',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
